import Footer from './Footer';
import Head from 'next/head';
import Header from './Header';

import React from 'react';

export default function Layout({children}: {children: React.ReactNode}) {
	return (
		<>
			<Head>
				<title>{"Adventurer's Tome"}</title>

				<meta
					name="description"
					content="Generated by create next app"
				/>

				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Alegreya+SC:wght@400;700;900&family=Alegreya+Sans+SC:wght@300;400;700;900&family=Alegreya+Sans:wght@300;400;700&family=Alegreya:wght@400;700;900&display=swap"
					rel="stylesheet"
				/>

				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main>{children}</main>

			<Footer />
		</>
	);
}
