import type {NextPage} from 'next';
import Footer from '../components/Footer';
import Head from 'next/head';
import Header from '../components/Header';
import Hero from '../components/Hero';
import LandingPostList from '../components/LandingPostList';
import Testimonials from '../components/Testimonials';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>{"Adventurer's Tome"}</title>

				<meta
					name="description"
					content="Generated by create next app"
				/>

				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main>
				<Hero />

				<div className="main-container">
					<Testimonials />

					<LandingPostList />
				</div>
			</main>

			<Footer />
		</div>
	);
};

export default Home;
